[package]
name = "xson"
version = "0.1.0"
edition = "2021"

[lib]
name = "xson"
# 生成供 JNI 调用的动态库
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simd-json = { version = "0.9", features = ["serde"] }


