[package]
name = "xson"
version = "0.1.0"
edition = "2021"

[lib]
name = "xson"
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

